# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 13:11
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='male', max_length=10, verbose_name='\u6027\u522b')),
                ('address', models.CharField(default='\u5317\u4eac', max_length=100, verbose_name='\u5730\u5740')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='\u624b\u673a\u53f7')),
                ('is_admin', models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u7ba1\u7406\u5458')),
                ('email', models.CharField(default='120@163.com', max_length=50, verbose_name='\u90ae\u7bb1')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpressProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='\u59d3\u540d')),
                ('phone', models.IntegerField(verbose_name='\u624b\u673a\u53f7')),
                ('area', models.TextField(verbose_name='\u5730\u533a')),
                ('address', models.TextField(verbose_name='\u5730\u5740')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.IntegerField(default=100, verbose_name='\u5feb\u9012\u5355\u53f7')),
                ('pname', models.CharField(choices=[('1', '\u987a\u4e30'), ('2', '\u5706\u901a'), ('3', '\u4e2d\u901a'), ('4', '\u767e\u4e16\u6c47\u4e30')], default='\u987a\u4e30', max_length=32, verbose_name='\u7269\u6d41\u540d\u79f0')),
                ('pinfo', models.CharField(choices=[('1', '\u6587\u4ef6'), ('2', '\u5305\u88f9')], default='\u6587\u4ef6', max_length=16, verbose_name='\u7269\u54c1\u7c7b\u578b')),
                ('pweight', models.FloatField(default=0.0, verbose_name='\u5feb\u9012\u91cd\u91cf')),
                ('psupport', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4fdd\u4ef7')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('pdeliver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliver_name', to='express_site.ExpressProfile', verbose_name='\u53d1\u4ef6\u4eba\u59d3\u540d')),
                ('preceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_name', to='express_site.ExpressProfile', verbose_name='\u6536\u4ef6\u4eba\u59d3\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='UserParcelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express_site.ParcelProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
