# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelprofile',
            name='pcost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='\u5feb\u9012\u8d39\u7528'),
        ),
        migrations.AddField(
            model_name='parcelprofile',
            name='pis_getmsg',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a5\u6536\u5bc4\u4ef6\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='parcelprofile',
            name='ptime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expressprofile',
            name='area',
            field=models.CharField(choices=[(1, '\u5317\u4eac\u5e02 \u671d\u9633\u533a \u9759\u5b89\u5e84'), (2, '\u5317\u4eac\u5e02 \u6d77\u6dc0\u533a \u4e2d\u5173\u6751'), (3, '\u5b89\u5fbd\u7701 \u5408\u80a5\u5e02 \u8700\u5c71\u533a'), (4, '\u5e7f\u4e1c\u7701 \u6df1\u5733\u5e02 \u5b9d\u5b89\u533a')], max_length=256, verbose_name='\u5730\u533a'),
        ),
    ]
