# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_site', '0002_auto_20180312_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressprofile',
            name='area',
            field=models.TextField(verbose_name='\u5730\u533a'),
        ),
        migrations.AlterField(
            model_name='expressprofile',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='\u624b\u673a\u53f7'),
        ),
        migrations.AlterField(
            model_name='parcelprofile',
            name='pcost',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='\u5feb\u9012\u8d39\u7528'),
        ),
        migrations.AlterField(
            model_name='parcelprofile',
            name='pinfo',
            field=models.CharField(default='\u6587\u4ef6', max_length=128, verbose_name='\u7269\u54c1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='parcelprofile',
            name='pnum',
            field=models.CharField(max_length=128, verbose_name='\u5feb\u9012\u5355\u53f7'),
        ),
        migrations.AlterField(
            model_name='parcelprofile',
            name='ptime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u5bc4\u4ef6\u65f6\u95f4'),
        ),
    ]
